### ISSUE TITLE
No entry 'bin\config.bin/CfgVehicles/EventHandlers.scope'.

### ISSUE THREAD

**Issue by F4BI** [mgkid3310/AWESome#31]
**Describe the bug**
Get error message "No entry 'bin\config.bin/CfgVehicles/EventHandlers.scope'." on startup

**To Reproduce**
Start Arma

**Expected behavior**
No error message

**Game Environment:**
 - Additional Addons: [CBA v3.9.1.181229(requiered)]
 - Date [e.g. 2018.06.14.]
 - Addon Version (If available) [v 1.1.1]

**Additional context**
after deleting orbis_aerodynamics.pbo the error doesn't appears

**Comment by mgkid3310** [comment]
Thanks for the report. Firstly, AFAIK the error message appears but does not do any harm to gameplay other than bothering on startup. Many other addons also occur that error, seems like addon system-based.
But since it's an interesting behavior that a specific pbo causes that error, I'll work on if I could remove the error message.

**Comment by F4BI** [comment]
Thanks for the fast response.
The Update fixes the bug and the error dosen´t appear anymore :)
