### ISSUE TITLE
Classify contact in ATC

### ISSUE THREAD

**Issue by osfrance** [mgkid3310/AWESome#66]
Hi, Thanks for your awesome work on awesome mod ;-)
Is a way to add a feature like ATC player can manually set contact by treat on military radar mode in the ATC Marker CGI ? (Hostile in red, Unknown in yellow, civilian in purple, and friendly in green) ?

It can be very cool to play in multiplayer with a ATC player and pilots ...

Many thanks !

**Comment by mgkid3310** [comment]
It might need some time, as
1) I need to figure out the UI or keybinding for this. Maybe pressing a key then clicking on marker set the threat type?
2) Currently the mod keeps unkown contact then if it shoots at friendly it's shown as hostile. If you want manual control over this, should the current behaviour be disabled or be kept? i.e. enabling the manual option disable automatic behaviour?
Let me know what you think about these points, coding itself might be easier than I think, it's more about the system design.

**Comment by osfrance** [comment]
If it's possible to display a menu on clicking on the CGI marker, it's fine. An option to disable the automatic classification is a good idea too.

**Comment by mgkid3310** [comment]
Progress update: manual classification feature is updated to GitHub, using a keybind
How it works: Current system stays the same. However, with a keybind clicking the marker while the keybind is pressed marks blue/civ/bogie markers to bandit, and bandit marker to its original states (ones that marnually marked from blue/civ to bandit goes back to blue/civ and bandits that came from bogies due to manual classification or automatic classification are reverted to bogie state)
Ig it would be better to try them out in-game. I've published the feature on Steam Workshop with v1.4.17.0, try it out and let me know who you feel.

**Comment by osfrance** [comment]
It's great ! Many thanks for your reactivity :-D

**Comment by osfrance** [comment]
Hi, I had another idea, it's possible to classifying contact "Hostile" or "neutral" ?
With this option we can now full classifying contacts (hostile, neutral, friendly and unknown), it can be great for ambiant ...
Many thanks !!!

**Comment by mgkid3310** [comment]
Sorry I missed the notification for a long time, for now AWESome is on a bugfix-only state. Moreover, adding keybinds for each state requires state management in vehicle side in radar background system, which can cause unkown problems and can lead to increased dev workload.

Again, sorry for way too late comment.
