### ISSUE TITLE
option to display ATIS in text

### ISSUE THREAD

**Issue by osfrance** [mgkid3310/AWESome#67]
Hi, 

It's possible to add an option to display ATIS in text ? 
Because it's not easy to understand atis TTS with the engine on and if players are not familiar with english speech ...

Many thanks,

**Comment by mgkid3310** [comment]
This would be pretty easy ig, what about adding an option (set True by default) to show ATIS on chat? For now the chat UI would be the best way to show text

**Comment by osfrance** [comment]
Oh yes, it's a good idea !

**Comment by mgkid3310** [comment]
* Option selection (default to hint)

![image](https://github.com/mgkid3310/AWESome/assets/28443711/fbaa6fd0-4927-4f37-99ed-1c01cd49286c)

* ATIS display with hint (hintSilent)

![image](https://github.com/mgkid3310/AWESome/assets/28443711/243c8a3a-1064-4f61-9aa9-3764a99924d8)

* ATIS display with systemChat

![image](https://github.com/mgkid3310/AWESome/assets/28443711/8db5ea77-8b46-4fef-adba-c16450fac72b)

Updated to GitHub with last commit, update to Steam will take some more time as I'm thinking of working on the classification feature now or later, due to UI issues

**Comment by mgkid3310** [comment]
Will close the issue once you check the comment and say ok

**Comment by osfrance** [comment]
Awesome work !!!! many thanks !!!!!
